messenger4j:
  appSecret: b2711704201854e6e78676c91d2fe2ec
  verifyToken : dogwalk
  pageAccessToken: EAAa5ea6KNKYBAHPr3hvE2kBPStDbd44QVDfpUvozCt877ZA2PQXaLR2vJ2BBw2vqECDBFE2eT0pYUp0zIodjC75UHTJHuDI0yUvwpqGNQo8FTwrcW1RujNVnZBesJmnCZBlbzqlt8aOLVHEa9mXQazmtTxFnAsny9LagPD7QgZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
